language: go

services:
  - mysql

go:
  # - 1.8.x
  - 1.9.x
  - master

sudo: false

before_install:
  - mysql -e "CREATE DATABASE comedian DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
  - go get -u github.com/pressly/goose/cmd/goose
  - $HOME/gopath/bin/goose -dir migrations mysql "root@/comedian" up
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls  -service=travis-ci

env:
- COMEDIAN_SLACK_TOKEN=$COMEDIAN_SLACK_TOKEN
- COMEDIAN_MANAGER_SLACK_USER_ID=$COMEDIAN_MANAGER_SLACK_USER_ID
- COMEDIAN_REPORTING_CHANNEL=$COMEDIAN_REPORTING_CHANNEL
- COMEDIAN_DATABASE=$COMEDIAN_DATABASE

- COMEDIAN_REPORT_TIME=$COMEDIAN_REPORT_TIME
- COMEDIAN_LANGUAGE=$COMEDIAN_LANGUAGE
- COMEDIAN_NOTIFIER_INTERVAL=$COMEDIAN_NOTIFIER_INTERVAL
- COMEDIAN_REMINDER_REPEATS_MAX=$COMEDIAN_REMINDER_REPEATS_MAX
- COMEDIAN_REMINDER_TIME=$COMEDIAN_REMINDER_TIME
- COMEDIAN_HTTP_BIND_ADDR=$COMEDIAN_HTTP_BIND_ADDR

- COMEDIAN_ENABLE_TEAM_MONITORING=$COMEDIAN_ENABLE_TEAM_MONITORING
- COMEDIAN_COLLECTOR_TOKEN=$COMEDIAN_COLLECTOR_TOKEN
- COMEDIAN_COLLECTOR_URL=$COMEDIAN_COLLECTOR_URL