language: go

services:
  - mysql

go:
  # - 1.8.x
  - 1.9.x
  - master

sudo: false

before_install:
  - mysql -e "CREATE DATABASE comedian DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
  - go get -u github.com/pressly/goose/cmd/goose
  - $HOME/gopath/bin/goose -dir migrations mysql "root@/comedian" up
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls  -service=travis-ci

env:
- DATABASE="root@/comedian?parseTime=true" HTTP_BIND_ADDR=":8080" NOTIFIER_CHECK_INTERVAL=60 MANAGER_SLACK_USER_ID=UB9AE7CL9 REPORT_TIME="15:26"