language: go
go:
  - master

services:
  - mysql

sudo: false

before_install:
  - mysql -e "CREATE DATABASE comedian DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
  - go get -u github.com/pressly/goose/cmd/goose
  - $GOPATH/bin/goose -dir migrations mysql "comedian:comedian@(localhost:3306)/comedian?parseTime=true" up
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls  -service=travis-ci

env:
  - COMEDIAN_DATABASE="comedian:comedian@(localhost:3306)/comedian?parseTime=true"  COMEDIAN_HTTP_BIND_ADDR=":8080"  COMEDIAN_SLACK_TOKEN="hello" COMEDIAN_NOTIFIER_CHECK_INTERVAL=15 COMEDIAN_MANAGER=manager COMEDIAN_DIRECT_MANAGER_CHANNEL_ID=someID COMEDIAN_REPORT_TIME=17:00 COMEDIAN_DEBUG=true