version: "2.4"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=comedian
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -proot -e 'SHOW DATABASES' > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  comedian:
    build: .
    ports:
      - 80:8090
    environment:
      - COMEDIAN_DATABASE=root:root@tcp(db:3306)/comedian?parseTime=true
      - COMEDIAN_SLACK_TOKEN=${COMEDIAN_SLACK_TOKEN}
      - COMEDIAN_MANAGER_SLACK_USER_ID=${COMEDIAN_MANAGER_SLACK_USER_ID}
      - COMEDIAN_MANAGER_SLACK_CHAN_GENERAL=${COMEDIAN_MANAGER_SLACK_CHAN_GENERAL}
      - COMEDIAN_COLLECTOR_TOKEN=${COMEDIAN_COLLECTOR_TOKEN}
      - COMEDIAN_COLLECTOR_URL=${COMEDIAN_COLLECTOR_URL}
      - COMEDIAN_REPORT_TIME=${COMEDIAN_REPORT_TIME}
      - COMEDIAN_LANGUAGE=${COMEDIAN_LANGUAGE}
      - COMEDIAN_NOTIFIER_INTERVAL=${COMEDIAN_NOTIFIER_INTERVAL}
      - COMEDIAN_REMINDER_REPEATS_MAX=${COMEDIAN_REMINDER_REPEATS_MAX}
      - COMEDIAN_REMINDER_TIME=${COMEDIAN_REMINDER_TIME}
    depends_on:
      db:
        condition: service_healthy