version: '3'

services:

  db:
    image: percona/percona-server:5.7 
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian

  comedian:
    image: anatoliyfedorenko/comedian
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      COMEDIAN_SLACK_TOKEN: ${COMEDIAN_SLACK_TOKEN}
      COMEDIAN_DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: 0.0.0.0:8080
      COMEDIAN_NOTIFIER_CHECK_INTERVAL: 60
      COMEDIAN_MANAGER: fedorenko.tolik
      COMEDIAN_DIRECT_MANAGER_CHANNEL_ID: CBAP453GV
      COMEDIAN_REPORT_TIME: '15:26'
      COMEDIAN_LANGUAGE: ru_RU
    depends_on:
      - "db"