version: '3'

services:

  db:
    image: percona/percona-server:5.7 
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: 
    healthcheck:
      test: ["CMD-SHELL", "mysql -u comedian -pcomedian -e 'SHOW DATABASES' > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  comedian:
    image: anatoliyfedorenko/comedian
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      COMEDIAN_SLACK_TOKEN: ${COMEDIAN_SLACK_TOKEN}
      COMEDIAN_DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: ${COMEDIAN_HTTP_BIND_ADDR}
      COMEDIAN_NOTIFIER_CHECK_INTERVAL: ${COMEDIAN_NOTIFIER_CHECK_INTERVAL}
      COMEDIAN_MANAGER_SLACK_USER_ID: ${COMEDIAN_MANAGER_SLACK_USER_ID}
      COMEDIAN_REPORT_TIME: ${COMEDIAN_REPORT_TIME}
      COMEDIAN_LANGUAGE: ${COMEDIAN_LANGUAGE}
      COMEDIAN_COLLECTOR_TOKEN: ${COMEDIAN_COLLECTOR_TOKEN}
      COMEDIAN_COLLECTOR_URL: ${COMEDIAN_COLLECTOR_URL}
      COMEDIAN_MANAGER_SLACK_CHAN_GENERAL: ${COMEDIAN_MANAGER_SLACK_CHAN_GENERAL}
    depends_on:
      db:
        condition: service_healthy