version: '3'

services:

  db:
    image: percona/percona-server:5.7 
    restart: on-failure
    environment:
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120

  comedian:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db:db
    env_file: .env
    depends_on:
      - "db"