version: "2.4"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=comedian
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -proot -e 'SHOW DATABASES' > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  comedian:
    image: golang:1.8
    working_dir: /go/src/github.com/maddevsio/comedian
    ports:
      - 80:8090
    volumes:
      - ./:/go/src/github.com/maddevsio/comedian
    command: go run main.go
    environment:
      - COMEDIAN_DB_CONNECTION_STRING=root:root@tcp(db:3306)/comedian?parseTime=true
    depends_on:
      db:
        condition: service_healthy
  tests:
    image: golang:1.8
    working_dir: /go/src/github.com/maddevsio/comedian
    ports:
      - 80:8090
    volumes:
      - ./:/go/src/github.com/maddevsio/comedian
    command: go test -cover -race ./api/ ./chat/ ./config/ ./notifier/ ./reporting/ ./storage/
    environment:
      - COMEDIAN_DB_CONNECTION_STRING=root:root@tcp(db:3306)/comedian?parseTime=true
    depends_on:
      db:
        condition: service_healthy