version: '3'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: mysql-serverpwd
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  comedian:
    build: .
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      COMEDIAN_DATABASE: comedian:mysql-serverpwd@(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: 0.0.0.0:8080
      COMEDIAN_SLACK_TOKEN: xoxb-286796085686-oMI9SJhavRlPMZTKti4mefhu

