version: '3'

services:

  db:
    image: percona/percona-server:5.7 
    restart: on-failure
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian
    volumes:
      - "./docker:/etc/mysql/conf.d"

  comedian:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      COMEDIAN_SLACK_TOKEN: ${COMEDIAN_SLACK_TOKEN}
      COMEDIAN_DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: ${COMEDIAN_HTTP_BIND_ADDR}
      COMEDIAN_NOTIFIER_INTERVAL: ${COMEDIAN_NOTIFIER_INTERVAL}
      COMEDIAN_HTTP_BIND_ADDR: ${COMEDIAN_HTTP_BIND_ADDR}
      COMEDIAN_MANAGER_SLACK_USER_ID: ${COMEDIAN_MANAGER_SLACK_USER_ID}
      COMEDIAN_REPORT_TIME: ${COMEDIAN_REPORT_TIME}
      COMEDIAN_LANGUAGE: ${COMEDIAN_LANGUAGE}
      COMEDIAN_COLLECTOR_TOKEN: ${COMEDIAN_COLLECTOR_TOKEN}
      COMEDIAN_COLLECTOR_URL: ${COMEDIAN_COLLECTOR_URL}
      COMEDIAN_MANAGER_SLACK_CHAN_GENERAL: ${COMEDIAN_MANAGER_SLACK_CHAN_GENERAL}
      COMEDIAN_REMINDER_REPEATS_MAX: ${COMEDIAN_REMINDER_REPEATS_MAX}
      COMEDIAN_REMINDER_TIME: ${COMEDIAN_REMINDER_TIME}
    depends_on:
      - db
