userExist = "Этот пользователь уже существует"
addUserNoStandupTime = "Пользователь <@%s> добавлен, но в этом канале не установлено время для стэндапов!"
addUser = "Пользователь <@%s> добавлен"

deleteUser = "Пользователь <@%s> удален"
listNoStandupers = "В этом канале нет стэндаперов! Чтобы добавить кого-нибдуь, используйте слэш команду `/comedianadd`"
listStandupers = "Стэндаперы в канале: %v"

addStandupTimeNoUsers = "<!date^%v^Срок для стэндапов установлен на {time}, но в этом канале нет стэндаперов>"
addStandupTime = "<!date^%v^Срок для стэндапов установлен на {time}|Срок для стэндапов установлен на 12:00>"
removeStandupTimeWithUsers = "Время для стэндапов в этом канале удалено, но остались стэндаперы!"
removeStandupTime = "Стэндап время для канала %s удалено" 

showNoStandupTime = "У этого канала до сих пор не установленно стэндап время! Пожалуйста, установите время слэшкомандой `/standuptimeset`!"
showStandupTime = "<!date^%v^Срок для стэндапов установлен на {time}|Срок для стэндапов установлен на 12:00>"

wrongNArgs = "Неверное количество аргументов. Перепроверьте свои данные!"
reportByProjectAndUser = "Данный пользователь не установлен как стэндапер в этом канале. Для начала добавьте его слэшкомандой `/comdeidanadd`"
reportOnProjectHead = "Полный отчёт по стэндапам <#%s|%s>:\n\n"
reportOnUserHead = "Полный отчет по пользователю <@%s>:\n\n"
reportOnProjectAndUserHead = "Стэндап отчет по проекту: <#%s>, пользователь: <@%s>\n\n"

reportNoData = "Нет данных за данный период"
reportPeriod = "\n\nОтчет с %s по %s:\n"
reportStandupFromUser = "\nСтэндап от <@%s>:\n%s\n"
reportStandupsFromProject = "\nНа проект: <#%s>\n%s\n"
reportIgnoredStandup = "\n<@%s>: стэндап успешно просран!\n"


HelloManager = "Привет, менеджер!"
StandupAccepted = "Отличная работа! Стэндап принят! Бомби дальше!"

p1 = "роблем"
p2 = "рудност"
p3 = "атрдуднен"

y1 = "чера"
y2 = "ятницу"
y3 = "делал"
y4 = "делано"
		
t1 = "егодн"
t2 = "обираюс"
t3 = "ланир"

notifyNotAll = "В этом канале не все написали стэндапы сегодня! %v - вам пиздец!"
notifyAllDone = "Поздравляю, сегодня все написали стэндапы!"
notifyManagerAllDone = "<@%v>, в канале <#%s> все написали стэндапы сегодня"
notifyManagerNotAll = "<@%v>, в канале <#%s> не все написали стэндапы сегодня, игнорировали: %v."
notifyUsersWarning = "Друзья, я всё еще жду стэндапы от вас! Если их не будет, вам пизда: %s"
notifyDirectMessage = "Привет, <@%s>! У тебя проёбан срок по стэндапам в канале <#%s>. Пожалуйста, напиши стэндап! Чем скорее тем лучше!"