reportOnProjectHead = "Full Report on project <#%s>:\n\n"
reportOnUserHead = "Full Report on user <@%s>:\n\n"
reportOnProjectAndUserHead = "Report on project: <#%s>, and user: <@%s>\n\n"

reportNoData = "No standup data for this period"
reportPeriod = "\n\nReport from %s to %s:\n"
reportStandupFromUser = "\nStandup from <@%s>:\n%s\n"
reportIgnoredStandup = "\n<@%s>: ignored standup!\n"
reportShowChannel = "In channel: <#%s>\n"