HelloManager = "Hello, Manager!"
StandupAccepted = "Good job! Standup accepted! Keep it up!"

p1 = "roblem"
p2 = "ifficul"
p3 = "tuck"

y1 = "esterday"
y2 = "riday"
y3 = "did"
y4 = "have done"
		
t1 = "oday"
t2 = "going to"
t3 = "plan"