HelloManager = "Привет, менеджер!"
StandupAccepted = "Отличная работа! Стэндап принят! Бомби дальше!"

p1 = "роблем"
p2 = "рудност"
p3 = "атрдуднен"

y1 = "чера"
y2 = "ятницу"
y3 = "делал"
y4 = "делано"
		
t1 = "егодн"
t2 = "обираюс"
t3 = "ланир"