notifyNotAll = "В этом канале не все написали стэндапы сегодня! %v - вам пиздец!"
notifyAllDone = "Поздравляю, сегодня все написали стэндапы!"
notifyManagerAllDone = "<@%v>, в канале <#%s> все написали стэндапы сегодня"
notifyManagerNotAll = "<@%v>, в канале <#%s> не все написали стэндапы сегодня, игнорировали: %v."
notifyUsersWarning = "Друзья, я всё еще жду стэндапы от вас! Если их не будет, вам пизда: %s"
notifyDirectMessage = "Привет, <@%s>! У тебя проёбан срок по стэндапам в канале <#%s>. Пожалуйста, напиши стэндап! Чем скорее тем лучше!"


noWorklogs = "недостаточно ворклогов: %v"
noCommits = "вообще нет коммитов, "
noStandup = "и где твой стэндап?"

hasWorklogs = "достаточно ворклогов: %v"
hasCommits = "коммиты есть: %v"
hasStandup = "а стэндап есть! Молодец! Но всё равно дрозда получишь!"

isRook = "<@%v> сграчевал! (%v)\n"