userExist = "Этот пользователь уже существует"
addUserNoStandupTime = "Пользователь <@%s> добавлен, но в этом канале не установлено время для стэндапов!"
addUser = "Пользователь <@%s> добавлен"
addAdmin = "Пользователь <@%s> добавлен как администратор"


deleteUser = "Пользователь <@%s> удален"
listNoStandupers = "В этом канале нет стэндаперов! Чтобы добавить кого-нибдуь, используйте слэш команду `/comedianadd`"
listStandupers = "Стэндаперы в канале: %v"

addStandupTimeNoUsers = "<!date^%v^Срок для стэндапов установлен на {time}, но в этом канале нет стэндаперов|Срок для стэндапов установлен на 12:00, но в этом канале нет стэндаперов>"
addStandupTime = "<!date^%v^Срок для стэндапов установлен на {time}|Срок для стэндапов установлен на 12:00>"
removeStandupTimeWithUsers = "Время для стэндапов в этом канале удалено, но остались стэндаперы!"
removeStandupTime = "Стэндап время для канала %s удалено" 

showNoStandupTime = "У этого канала до сих пор не установленно стэндап время! Пожалуйста, установите время слэшкомандой `/standuptimeset`!"
showStandupTime = "<!date^%v^Срок для стэндапов установлен на {time}|Срок для стэндапов установлен на 12:00>"

wrongNArgs = "Неверное количество аргументов. Перепроверьте свои данные!"
reportByProjectAndUser = "Данный пользователь не установлен как стэндапер в этом канале. Для начала добавьте его слэшкомандой `/comdeidanadd`"
reportOnProjectHead = "Полный отчет по проекту <#%s> с %v по %v:\n\n"
reportOnUserHead = "Полный отчет по пользователю <@%s> с %v по %v:\n\n"
reportOnProjectAndUserHead = "Отчет по проекту: <#%s>, пользователь: <@%s> с %v по %v:\n\n"

reportNoData = "Нет данных за данный день"
reportDate = "Отчет за %s:\n"
reportStandupFromUser = "\nСтэндап от <@%s>:\n%s\n"
reportIgnoredStandup = "\n<@%s>: стэндап пропущен!\n"
reportShowChannel = "В канале: <#%s>"
reportCollectorDataUser = "\n\nКоммитов: %v \nМержей: %v\nЧасов ворклогов: %v"
dateError1 = "Дата начала больше чем дата конца периуда"
dateError2 = "Дата конца отчёта указана в будущем времени"
userDidNotStandup = "<@%v> не написал стэндап!\n"
userDidStandup = "<@%v> написал стэндап!\n"
userDidNotStandupInChannel = "В <#%v> <@%v> не написал стэндап!\n"
userDidStandupInChannel = "В <#%v> <@%v> написал стэндап!\n"


helloManager = "Привет, менеджер!"
standupAccepted = "Отличная работа! Стэндап принят! Бомби дальше!"

p1 = "роблем"
p2 = "рудност"
p3 = "атрдуднен"

y1 = "чера"
y2 = "ятницу"
y3 = "делал"
y4 = "делано"
		
t1 = "егодн"
t2 = "обираюс"
t3 = "ланир"

notifyNotAll = "В этом канале не все написали стэндапы сегодня! %v - вы грачи!"
notifyAllDone = "Поздравляю, сегодня все написали стэндапы!"
notifyManagerAllDone = "<@%v>, в канале <#%s> все написали стэндапы сегодня"
notifyManagerNotAll = "<@%v>, в канале <#%s> не все написали стэндапы сегодня, игнорировали: %v."
notifyUsersWarning = "%v, команда всё еще ждет стэндапы от вас! Осталось %v минут до дедлайна!"
notifyDirectMessage = "Привет, <@%s>! У тебя пропущен срок по стэндапам в канале <#%s>. Пожалуйста, напиши стэндап! Чем скорее тем лучше!"


noWorklogs = "недостаточно ворклогов: %v"
noCommits = "вообще нет коммитов, "
noStandup = "и где твой стэндап?"

hasWorklogs = "достаточно ворклогов: %v"
hasCommits = "коммиты есть: %v"
hasStandup = "а стэндап есть! Молодец!"

isRook = "<@%v> сграчевал в проекте <#%v>! (%v)\n"